#!/bin/sh

if [ -z "${CC}" ]; then
	CC="c99"
fi

if [ -z "$1" ]; then
	OPTION="all"
else
	OPTION="$1"
fi

echo "Build options:"
echo "CC\t\t= ${CC}"
echo "Option\t\t= ${OPTION}"

case $OPTION in
	clean)
		find ./ -type f -ipath "./*.*/a.out" \
			-exec rm -vf {} \;
			break
			;;
	*)
		find ./ -type f -ipath "./*.*/*.c" \
			-exec sh -c "echo \"Compilig\" \$0 to \"\$(dirname \$0)/a.out\"" {} \; \
			-exec sh -c "${CC} -o \"\$(dirname \$0)/a.out\" \$0" {} \;
			break
			;;
esac
